# Generated by Django 3.2.7 on 2021-09-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('image', models.ImageField(default='/profile_pics/default.jpg', upload_to='profile_pics')),
                ('description', models.TextField()),
                ('car_published_year', models.CharField(default='', max_length=200)),
                ('color', models.CharField(max_length=255)),
                ('fuel_type', models.CharField(max_length=255)),
            ],
        ),
    ]
